// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMPbwx_SAEyrxqV_lU04Gdxn36njMg5o',
    appId: '1:404064594126:web:69b8042ebc597de674c89f',
    messagingSenderId: '404064594126',
    projectId: 'agriapp-12788',
    authDomain: 'agriapp-12788.firebaseapp.com',
    storageBucket: 'agriapp-12788.appspot.com',
    measurementId: 'G-R3F9R9Y8KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtsMOLUfc8j_wj1VMukkFQ_aHie6Wf_g',
    appId: '1:404064594126:android:73cf52c2ecfcb98e74c89f',
    messagingSenderId: '404064594126',
    projectId: 'agriapp-12788',
    storageBucket: 'agriapp-12788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvrQlf6jkADoc0ei8hbcimeRzDTHt8jI',
    appId: '1:404064594126:ios:09e06c6097b3bf1c74c89f',
    messagingSenderId: '404064594126',
    projectId: 'agriapp-12788',
    storageBucket: 'agriapp-12788.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvrQlf6jkADoc0ei8hbcimeRzDTHt8jI',
    appId: '1:404064594126:ios:09e06c6097b3bf1c74c89f',
    messagingSenderId: '404064594126',
    projectId: 'agriapp-12788',
    storageBucket: 'agriapp-12788.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLMPbwx_SAEyrxqV_lU04Gdxn36njMg5o',
    appId: '1:404064594126:web:38446b2a4cd711f074c89f',
    messagingSenderId: '404064594126',
    projectId: 'agriapp-12788',
    authDomain: 'agriapp-12788.firebaseapp.com',
    storageBucket: 'agriapp-12788.appspot.com',
    measurementId: 'G-DSDGSD5B7J',
  );

}